#!/usr/bin/env ruby

def sh(cmd)
  puts cmd
  system cmd
end

if ARGV.size == 0
  puts "usage: #$0 file"
else
  path = ARGV[0]
  case File.extname(path).downcase[1..-1]
  when "png", "jpg", "gif"
    sh "pqiv -i '#{path}' &"
  when "xls", "xlsx", "ods",
       "doc", "docx", "odt"
    sh "libreoffice '#{path}' &"
  when "pdf"
    sh "acroread '#{path}' &"
  when "html"
    sh "chromium-browser '#{path}' &"
  else
    if File.directory?(path)
      sh "nautilus #{path} &"
    else
      $stderr.puts "don't know how to open #{path} (#{File.extname(path)})"
      exit 1
    end
  end
end
